name: Publish
on: [workflow_dispatch]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        env: 
          APIKEY: ${{ APIKEY }}
        run: .\publish.ps1
        shell:pwsh
